name: Original Music by Gabriel Dib
favicon: null
layout_spectrum: 0.013259093975648284
typography_spectrum: 0.17673232546076179
title: 'Gabriel Dib, Composer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44416466-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3415607651695609
  lightness: 0.2423888873308897
  saturation: 0.21213683323003352
  rhythmicContrast: 0.2767810367513448
purpose: []
