name: Original Music by Gabriel Dib
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9116
title: 'Gabriel Dib, Composer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44416466-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.625
  lightness: 0.2423888873308897
  saturation: 0.375
  rhythmicContrast: 0.2767810367513448
purpose: []
