name: Original Music by Gabriel Dib
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9116
title: 'Gabriel Dib, Composer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44416466-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#0a0909'
    - '#dbdbdb'
    - '#735342'
    - '#9f9c94'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
